"""
Django settings for tfn_ctv project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Get SECRET_KEY from environment variable or use default for development
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-yu!84b5rz0^s6uz96@0tq^r)7eoz#o&&@)u+dnzqti0%24$+_g')

# SECURITY WARNING: don't run with debug turned on in production!
# Get DEBUG from environment variable (default to True for development)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Set ALLOWED_HOSTS based on environment
# In production, this should be a comma-separated list of domains
# For development, we allow localhost and 127.0.0.1
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    # Django CMS admin style (commented out - install django-cms packages to enable)
    # 'djangocms_admin_style',

    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Django CMS core apps (commented out - install django-cms packages to enable)
    # 'cms',
    # 'menus',
    # 'treebeard',
    # 'sekizai',

    # Django CMS plugins (commented out - install django-cms packages to enable)
    # 'djangocms_text_ckeditor',
    # 'djangocms_link',
    # 'djangocms_file',
    # 'djangocms_picture',
    # 'djangocms_video',
    # 'djangocms_style',
    # 'djangocms_audio',

    # Project apps
    'music_beta.apps.MusicBetaConfig',
    'artist_portal.apps.ArtistPortalConfig',
    # 'whitenoise.runserver_nostatic',  # Commented out - install whitenoise to enable
    # 'bootstrap5',  # Commented out - install django-bootstrap5 to enable
    'rest_framework',
]

# Django CMS settings
# SITE_ID = 1

# CMS_TEMPLATES = [
#     ('cms_home.html', 'Home Template'),
#     ('cms_page.html', 'Content Page'),
#     ('cms_sidebar.html', 'Page with Sidebar'),
# ]

# CMS_PERMISSION = True
# CMS_PLACEHOLDER_CONF = {}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',  # Commented out - install whitenoise to enable
    'tfn_ctv.rate_limiting.RateLimitMiddleware',

    # Django CMS middleware
    # 'django.middleware.locale.LocaleMiddleware',
    # 'cms.middleware.user.CurrentUserMiddleware',
    # 'cms.middleware.page.CurrentPageMiddleware',
    # 'cms.middleware.toolbar.ToolbarMiddleware',
    # 'cms.middleware.language.LanguageCookieMiddleware',
]

ROOT_URLCONF = 'tfn_ctv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.static',
                # 'sekizai.context_processors.sekizai',  # Django CMS - commented out
                # 'cms.context_processors.cms_settings',  # Django CMS - commented out
            ],
        },
    },
]

WSGI_APPLICATION = 'tfn_ctv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ['username', 'email', 'first_name', 'last_name'],
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'tfn_ctv.password_validation.ComplexityValidator',
        'OPTIONS': {
            'min_upper': 1,
            'min_lower': 1,
            'min_digits': 1,
            'min_special': 1,
        }
    },
]

# Password policy settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours in seconds
PASSWORD_EXPIRY_DAYS = 90  # Password expires after 90 days
PASSWORD_HISTORY_COUNT = 5  # Remember last 5 passwords to prevent reuse

# Security settings for cookies and HTTPS
# These settings are only applied when DEBUG is False (production)
if not DEBUG:
    # Secure cookie settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Django CMS language settings
LANGUAGES = [
    ('en', 'English'),
]

CMS_LANGUAGES = {
    1: [
        {
            'code': 'en',
            'name': 'English',
            'fallbacks': ['en'],
            'public': True,
            'hide_untranslated': False,
            'redirect_on_fallback': False,
        },
    ],
    'default': {
        'fallbacks': ['en'],
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User model
AUTH_USER_MODEL = 'music_beta.User'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
DEFAULT_FROM_EMAIL = 'noreply@tfnms.co'
DEVELOPER_EMAIL = 'developer@tfnms.co'  # Development email for form submissions
# TODO
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'your-email@gmail.com'           # Replace with your sender email
# EMAIL_HOST_PASSWORD = 'your-email-app-password'    # Use app password or environment variable
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'LOCATION': BASE_DIR / 'media',

    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        'LOCATION': BASE_DIR / 'static',
    }


}
